spring:
  # 데이터베이스 연결 설정
  datasource: # 여러 DBaaS에서 가져오기
    url: ${MYSQL_URL} # 데이터베이스 URL
    username: ${MYSQL_USER} # 데이터베이스 사용자 이름
    password: ${MYSQL_PASSWORD} # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

# 로깅 설정
logging:
  level:
    com:
      cake7:
        guestbook:
          mapper: ERROR # mapper 패키지의 로깅 레벨을 DEBUG로 설정 (DEV)